### ISSUE TITLE
Add Tool Information to the UI

### ISSUE THREAD

**Issue by berkingurcan** [UmstadAI/zkAppUmstad#43]
zkApp Umstad uses multiple tools like doc, issue, code, project. However, in the UI we cannot see which one is used or using while Umstad preparing answer.

It is difficult to pass tool information to the UI because the POST request returns stream as a StreamingTextResponse type
https://github.com/UmstadAI/zkAppUmstad/blob/main/app/api/chat/route.ts#L175

**TODO**
- [ ] Find a way to pass tool information(tool or function name is enough) to the UI
- [ ] Implement passing using tool information to the UI in real time or as stream
- [ ] Create Simple and good looking UI component for tool usage in the chat

**BONUS TODO**
- [ ] Store used tool info to the Vercel KV Database
- [ ] Get stored tool info from the Vercel KV Database while getting Chat
- [ ] Implement also used tools to Chat UI same as todo above.
